package slogo.model.coderunner;

import java.util.HashMap;
import java.util.Map;
import slogo.model.api.exception.coderunner.ErrorType;
import slogo.model.api.exception.coderunner.RunCodeError;
import slogo.model.command.Command;
import slogo.model.command.UserCommand;

/**
 * Represents an environment frame in the Slogo environment which supports closure for variables and
 * commands.
 *
 * @author Jason Qiu
 */
class Environment {

  Environment(Environment parent) {
    this.parent = parent;
    this.commandMap = new HashMap<>();
    this.variableMap = new HashMap<>();
  }

  Map<String, Double> getLocalVariables() {
    return new HashMap<>(variableMap);
  }

  /**
   * Returns all command names and metadata like parameter names and command definition defined
   * within this environment frame.
   *
   * @return an immutable map where the key is the command name and the value is the map of
   * metadata, including parameter names and command definition.
   */
  Map<String, Map<String, String>> getLocalCommands() {
    Map<String, Map<String, String>> commands = new HashMap<>();
    for (Map.Entry<String, Command> entry : commandMap.entrySet()) {
      if (!(entry.getValue() instanceof UserCommand command)) {
        continue;
      }
      Map<String, String> metadata = new HashMap<>();
      metadata.put("arity", Integer.toString(command.getArity()));
      for (int i = 0; i < command.getArity(); i++) {
        metadata.put("parameter" + (i + 1), command.getParameters().get(i));
      }
      metadata.put("body", command.getBodySource());
      commands.put(entry.getKey(), metadata);
    }
    return commands;
  }

  /**
   * Looks up a variable in this environment frame or its parents and returns the value.
   *
   * @param variableName the name of the variable
   * @return the value of the variable if found
   * @throws RunCodeError if the variable is not found
   */
  double lookupVariable(Token variableName) throws RunCodeError {
    if (!variableMap.containsKey(variableName.literal())) {
      if (parent == null) {
        throw ErrorFactory.createError(ErrorType.RUNTIME, "variableNotFound", variableName);
      }
      return parent.lookupVariable(variableName);
    }
    return variableMap.get(variableName.literal());
  }

  /**
   * Looks up a command by name in this environment frame or its parents and returns the command
   * object.
   *
   * @param commandName the name of the command
   * @return the command object if found
   * @throws RunCodeError if the command is not found
   */
  Command lookupCommand(Token commandName) throws RunCodeError {
    if (!commandMap.containsKey(commandName.literal())) {
      if (parent == null) {
        throw ErrorFactory.createError(ErrorType.RUNTIME, "commandNotFound", commandName);
      }
      return parent.lookupCommand(commandName);
    }
    return commandMap.get(commandName.literal());
  }

  /**
   * Sets/updates a variable
   *
   * @param name  the variable name
   * @param value the new value
   */
  void setVariable(String name, double value) {
    variableMap.put(name, value);
  }

  /**
   * Sets/updates a command
   *
   * @param name    the command name
   * @param command the new command instance
   */
  void defineCommand(String name, Command command) {
    commandMap.put(name, command);
  }

  void defineAlias(String alias, String commandName) {
    defineCommand(alias, lookupCommand(new Token(TokenType.COMMAND, commandName, -1,
        "autogenerated by aliasing")));
  }

  private final Environment parent;
  private final Map<String, Command> commandMap;
  private final Map<String, Double> variableMap;
}
