package slogo.model.coderunner;

import java.util.List;

/**
 * Represents all interpretable objects.
 *
 * @author Jason Qiu (GENERATED BY ExpressionClassGenerator.java)
 */

public abstract class Expression {

  interface Visitor {

    double visitNumber(Number expression);

    double visitBinary(Binary expression);

    double visitUnary(Unary expression);

    double visitVariable(Variable expression);

    double visitCall(Call expression);

    double visitBlock(Block expression);

    double visitMake(Make expression);

    double visitFor(For expression);

    double visitIfElse(IfElse expression);

    double visitTo(To expression);

    double visitTurtles(Turtles expression);

    double visitTell(Tell expression);

    double visitAsk(Ask expression);

    double visitAskWith(AskWith expression);
  }

  abstract double accept(Visitor visitor);


  public static class Number extends Expression {

    Number(double value) {
      super();
      this.value = value;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitNumber(this);
    }

    public double getValue() {
      return value;
    }

    private final double value;
  }

  public static class Binary extends Expression {

    Binary(Token operator, Expression left, Expression right) {
      super();
      this.operator = operator;
      this.left = left;
      this.right = right;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitBinary(this);
    }

    public Token getOperator() {
      return operator;
    }

    public Expression getLeft() {
      return left;
    }

    public Expression getRight() {
      return right;
    }

    private final Token operator;
    private final Expression left;
    private final Expression right;
  }

  public static class Unary extends Expression {

    Unary(Token operator, Expression right) {
      super();
      this.operator = operator;
      this.right = right;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitUnary(this);
    }

    public Token getOperator() {
      return operator;
    }

    public Expression getRight() {
      return right;
    }

    private final Token operator;
    private final Expression right;
  }

  public static class Variable extends Expression {

    Variable(Token name) {
      super();
      this.name = name;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitVariable(this);
    }

    public Token getName() {
      return name;
    }

    private final Token name;
  }

  public static class Call extends Expression {

    Call(Token commandName) {
      super();
      this.commandName = commandName;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitCall(this);
    }

    public Token getCommandName() {
      return commandName;
    }

    private final Token commandName;
  }

  public static class Block extends Expression {

    Block(List<Expression> body, String bodySource) {
      super();
      this.body = body;
      this.bodySource = bodySource;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitBlock(this);
    }

    public List<Expression> getBody() {
      return body;
    }

    public String getBodySource() {
      return bodySource;
    }

    private final List<Expression> body;
    private final String bodySource;
  }

  public static class Make extends Expression {

    Make(Token variable, Expression value) {
      super();
      this.variable = variable;
      this.value = value;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitMake(this);
    }

    public Token getVariable() {
      return variable;
    }

    public Expression getValue() {
      return value;
    }

    private final Token variable;
    private final Expression value;
  }

  public static class For extends Expression {

    For(Token iterator, Expression start, Expression end, Expression increment, Block body) {
      super();
      this.iterator = iterator;
      this.start = start;
      this.end = end;
      this.increment = increment;
      this.body = body;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitFor(this);
    }

    public Token getIterator() {
      return iterator;
    }

    public Expression getStart() {
      return start;
    }

    public Expression getEnd() {
      return end;
    }

    public Expression getIncrement() {
      return increment;
    }

    public Block getBody() {
      return body;
    }

    private final Token iterator;
    private final Expression start;
    private final Expression end;
    private final Expression increment;
    private final Block body;
  }

  public static class IfElse extends Expression {

    IfElse(Expression predicate, Expression trueBranch, Expression falseBranch) {
      super();
      this.predicate = predicate;
      this.trueBranch = trueBranch;
      this.falseBranch = falseBranch;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitIfElse(this);
    }

    public Expression getPredicate() {
      return predicate;
    }

    public Expression getTrueBranch() {
      return trueBranch;
    }

    public Expression getFalseBranch() {
      return falseBranch;
    }

    private final Expression predicate;
    private final Expression trueBranch;
    private final Expression falseBranch;
  }

  public static class To extends Expression {

    To(Token commandName, List<Token> parameters, Block body) {
      super();
      this.commandName = commandName;
      this.parameters = parameters;
      this.body = body;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitTo(this);
    }

    public Token getCommandName() {
      return commandName;
    }

    public List<Token> getParameters() {
      return parameters;
    }

    public Block getBody() {
      return body;
    }

    private final Token commandName;
    private final List<Token> parameters;
    private final Block body;
  }

  public static class Turtles extends Expression {

    Turtles() {
      super();
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitTurtles(this);
    }

  }

  public static class Tell extends Expression {

    Tell(List<Expression> ids) {
      super();
      this.ids = ids;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitTell(this);
    }

    public List<Expression> getIds() {
      return ids;
    }

    private final List<Expression> ids;
  }

  public static class Ask extends Expression {

    Ask(List<Expression> ids, Block body) {
      super();
      this.ids = ids;
      this.body = body;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitAsk(this);
    }

    public List<Expression> getIds() {
      return ids;
    }

    public Block getBody() {
      return body;
    }

    private final List<Expression> ids;
    private final Block body;
  }

  public static class AskWith extends Expression {

    AskWith(Expression predicate, Block body) {
      super();
      this.predicate = predicate;
      this.body = body;
    }

    @Override
    double accept(Visitor visitor) {
      return visitor.visitAskWith(this);
    }

    public Expression getPredicate() {
      return predicate;
    }

    public Block getBody() {
      return body;
    }

    private final Expression predicate;
    private final Block body;
  }

}
