package slogo.model.coderunner;

enum TokenType {
  // KEYWORDS
  MAKE, REPEAT, DOTIMES, FOR, IF, IFELSE, TO, ID, TURTLES, TELL, ASK, ASKWITH, // AGGREGATES
  NUMBER, VARIABLE, COMMAND, // OPERATORS
  PLUS, MINUS, STAR, FORWARD_SLASH, TILDA, PERCENT, // LOGIC
  EQUAL_TO, NOT_EQUAL_TO, GREATER_THAN, LESS_THAN, GREATER_EQUAL_TO, LESS_EQUAL_TO, // PUNCTUATION
  LEFT_SQUARE_BRACKET, RIGHT_SQUARE_BRACKET, EOF
}
